name: Build krp-curl Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
        default: 'v0.0.3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: quay.io/lcomellini/krp-curl
          tags: |
            type=raw,value=${{ inputs.version }}

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: examples/example-client/Dockerfile
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: mode=max
          sbom: true
